[package]
name = "viode-gui"
version.workspace = true
edition.workspace = true
license-file.workspace = true

[dependencies]
viode-core = { path = "../viode-core" }
anyhow.workspace = true
eframe = "0.32"
toml.workspace = true
serde_json.workspace = true
gstreamer.workspace = true
gstreamer-editing-services.workspace = true
gstreamer-app.workspace = true
gstreamer-video.workspace = true
image = { version = "0.25", default-features = false, features = ["png"] }

[dev-dependencies]
tempfile = "3"
