[package]
name = "viode-core"
version.workspace = true
edition.workspace = true

[dependencies]
serde.workspace = true
serde_json.workspace = true
toml.workspace = true
thiserror.workspace = true
gstreamer.workspace = true
gstreamer-editing-services.workspace = true
gstreamer-pbutils.workspace = true
